### ISSUE TITLE
Support for robotsflag field based on OpenWayback behaviour

### ISSUE THREAD

**Issue by anjackson** [nla/outbackcdx#4]
We were looking at using the `<robotstxt>` field, which is [currently not supported by tinycdxserver](https://github.com/nla/tinycdxserver/blob/master/src/tinycdxserver/XmlQuery.java#L122), and were wondering if you'd be happy for us to submit a pull request that enables it?

The implementation in OpenWayback is rather odd, in that it populate this field using the `M meta tags (AIF)` field (see [here](https://github.com/iipc/openwayback/blob/829693b6d43f40b1b045f08611a4fa5e27395e29/wayback-core/src/main/java/org/archive/wayback/resourceindex/cdx/format/CDXFlexFormat.java#L81-L85)). It's not clear why the `meta tags` field becomes the `robotstxt` field, but AFAICT this is the only way to populate that field via the [CDX format](http://iipc.github.io/warc-specifications/specifications/cdx-format/cdx-2015/).

It doesn't look like too difficult a change, but given that [it's nearly there but commented out](https://github.com/nla/tinycdxserver/blob/master/src/tinycdxserver/Capture.java#L162) I thought I'd better ask if there's a problem?  Presumably the indexes won't be compatible either?

**Comment by ato** [comment]
Sure, would be happy to accept a pull request that implements it.

There's no problem with it. The index format includes a pre-record (per CDX line) version number. So create a new ddcodd

**Comment by ato** [comment]
Gah. Sorry. 'close issue' is too near the text box on mobile. 

...  So create a new Capture.decodeValueV2() method for a version 2 record format that supports the robots field and update Capture.encodeValue() to write the new format. Then the index server will happily read both new and old records and you can even mix them in the one index while incrementally reindexing to fill in the robots field data. 

It was marked as todo simply because I didn't have any CDX files on hand with that field populated and wasn't sure what the data format was or what exactly it was used for in Wayback.
